# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 798490281186ffeebc822593eaf2bc9aef8d06e6d9a9eda3ea97aca876e3dfc3cb21da42994b2cd38e8f541fa1e6b23fff470c013d18caa6aaaa7dcebfa2fc1c

test:
  secret_key_base: 7c48a7872b8a434e5e7f0509166f357f7c7adc76595b84c26ea931da812d37cd2c456e7654fb24aeb795a148471c0440dae1f4ec35b01387ccfcfac0226866cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
